### ISSUE TITLE
Momey leak

### ISSUE THREAD

**Issue by mzouink** [janelia-cellmap/dacapo#349]
After the new version 
there is a memory leak
I think it is coming from funlib.persistence
Because funlib.show.neuroglancer is becoming really slow and buggy

<img width="716" alt="Screenshot 2024-11-23 at 1 42 27 PM" src="https://github.com/user-attachments/assets/c8be95c4-8701-42b9-975e-e285f290bdb1">

@pattonw

**Comment by pattonw** [comment]
Interesting. You're just visualizing an array with funlib show neuroglancer and it's using 500gb?

**Comment by mzouink** [comment]
no no, that graph is from dacapo train job. but i mentioned neuroglancer as side example

**Comment by pattonw** [comment]
Can you provide some (ideally simplified) config combination that leads to a similar memory profile?

**Comment by mzouink** [comment]
I don't know how to give you this exact code because i was using +200 nrs crops, but this iss the code i was running: 
(do you still have access to the cluster ?)
```python
# %%
import csv
import json
import os
import dacapo

# %%
datasplit_path = "datasplit_v2.csv"
classes_to_be_used_path = "to_be_used_v2.json"
#%%
with open(classes_to_be_used_path, 'r') as f:
    classes = ["bg"]+list(json.load(f).keys())
# %%
from dacapo.experiments.datasplits import DataSplitGenerator
from funlib.geometry import Coordinate
from dacapo.store.create_store import create_config_store
config_store = create_config_store()
# %%
from dacapo.experiments.datasplits import DataSplitGenerator
from funlib.geometry import Coordinate

input_resolution = Coordinate(8, 8, 8)
output_resolution = Coordinate(8,8,8)
datasplit_config = DataSplitGenerator.generate_from_csv(
    datasplit_path,
    input_resolution,
    output_resolution,
    # targets=classes,
    name="base_model_20241120_20_target_classes",
    # max_validation_volume_size = 400**3,
).compute()
# %%

datasplit = datasplit_config.datasplit_type(datasplit_config)

config_store.store_datasplit_config(datasplit_config)
# %%

from dacapo.experiments.tasks import  OneHotTaskConfig,

simple_one_hot = OneHotTaskConfig(
        name="one_hot_task",
        classes=classes,
        kernel_size=1,
    )
config_store.store_task_config(simple_one_hot)
# %%
from dacapo.experiments.architectures import CNNectomeUNetConfig
architecture_config = CNNectomeUNetConfig(
    name="simple_unet",
    input_shape=(2, 132, 132),
    eval_shape_increase=(8, 32, 32),
    fmaps_in=1,
    num_fmaps=8,
    fmaps_out=8,
    fmap_inc_factor=2,
    downsample_factors=[(1, 4, 4), (1, 4, 4)],
    kernel_size_down=[[(1, 3, 3)] * 2] * 3,
    kernel_size_up=[[(1, 3, 3)] * 2] * 2,
    constant_upsample=True,
    padding="valid",
)
config_store.store_architecture_config(architecture_config)
# %%
from dacapo.experiments.trainers import GunpowderTrainerConfig

trainer_config = GunpowderTrainerConfig(
    name="default_v3",
    batch_size=2,
    learning_rate=0.0001,
    num_data_fetchers=20,
    augments=[
        ElasticAugmentConfig(
            control_point_spacing=[100, 100, 100],
            control_point_displacement_sigma=[10.0, 10.0, 10.0],
            rotation_interval=(0, math.pi / 2.0),
            subsample=8,
            uniform_3d_rotation=True,
        ),
        IntensityAugmentConfig(
                    scale=(0.25, 1.75),
                    shift=(-0.5, 0.35),
                    clip=True,
                ),
        GammaAugmentConfig(gamma_range=(0.5, 2.0)),
                IntensityScaleShiftAugmentConfig(scale=2, shift=-1),
    ],
    snapshot_interval=100000,
    clip_raw=False,
)
config_store.store_trainer_config(trainer_config)
# %%
from dacapo.experiments import RunConfig
from dacapo.experiments.run import Run

iterations = 1000000
validation_interval = 10000
run_config = RunConfig(
    name=f"simple_base_model",
    datasplit_config=datasplit_config,
    task_config=simple_one_hot,
    architecture_config=architecture_config,
    trainer_config=trainer_config,
    num_iterations=iterations,
    validation_interval=validation_interval,
)
config_store.store_run_config(run_config)
# %%
# i submitted it in different job $ dacapo train run_name
from dacapo import train
train(run_config.name)
```

**Comment by pattonw** [comment]
Ah, so this might not be a memory leak, just lots of data.
Do you get the same pattern if you train with just 1 dataset?
How many iterations did you train before memory became a problem?

**Comment by mzouink** [comment]
Usually is not a problem even if there is a lot of data, because of the lazy loading. 
The error happens after ~ 1000 iterations 
i will try multiple scenario to narrow down the problem and come back.

**Comment by mzouink** [comment]
i submitted :
datasplit [1 crop , 100 crop]
Trainer [basid, with 3d augmentation]
each with 3 reperations
3 reperations of big datasplit hit the out of memory in the same time (with both trainers) r
~2600 iterations
the one crop datasplit is still running
so there is a memory leak in holding crops info per time.

**Comment by pattonw** [comment]
It could be the dask array, but we never call persist, and I'm pretty sure using `compute` doesn't cache data in memory

**Comment by mzouink** [comment]
now it is clear that is related to high number of crops. but i don't know how can i narrow the reason of the bug more

**Comment by pattonw** [comment]
My best guess is the masking.
Can you try replacing [this line](https://github.com/janelia-cellmap/dacapo/blob/1df45dbbef67522e7b096a0324c2f18348de04d1/dacapo/experiments/trainers/gunpowder_trainer.py#L203), with a `dask.array.ones(dataset.gt.data.shape, dtype=dataset.gt.data.dtype)` and see if that solves it?

**Comment by mzouink** [comment]
didn't work :/

**Comment by mzouink** [comment]
Hi Will, you need to keep running the scripts of at least an hour. because generating the random crops takes ~2000 sec
then i hit this error form your script :
![Screenshot 2024-12-03 at 10 14 16 AM](https://github.com/user-attachments/assets/13798a5b-ea3a-47ae-a1b7-ba519bc7f576)
```
Creating FileConfigStore:
	path: /groups/cellmap/cellmap/zouinkhim/base_model/dacapo_files/configs
Training run test_run_will_3ddd
Creating FileConfigStore:
	path: /groups/cellmap/cellmap/zouinkhim/base_model/dacapo_files/configs
Starting/resuming training for run test_run_will_3ddd...
Creating FileStatsStore:
	path    : /groups/cellmap/cellmap/zouinkhim/base_model/dacapo_files/stats
Traceback (most recent call last):
 File "/groups/cellmap/cellmap/zouinkhim/base_model/generate_run/profile_test_runs_3d_.py", line 128, in <module>
   train(run_config.name)
 File "/groups/cellmap/cellmap/zouinkhim/dacapo_release/dacapo/dacapo/train.py", line 47, in train
   return train_run(run, do_validate)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/groups/cellmap/cellmap/zouinkhim/dacapo_release/dacapo/dacapo/train.py", line 66, in train_run
   run.validation_scores.scores = stats_store.retrieve_validation_iteration_scores(
   ^^^^^^^^^^^^^^^^^^^^^
 File "/groups/cellmap/cellmap/zouinkhim/dacapo_release/dacapo/dacapo/experiments/run.py", line 160, in validation_scores
   self.datasplit.validate,
   ^^^^^^^^^^^^^^^^^^^^^^^
 File "/groups/cellmap/cellmap/zouinkhim/dacapo_release/dacapo/dacapo/experiments/datasplits/simple_config.py", line 69, in validate
   for x in self.get_paths(self.validate_group_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/groups/cellmap/cellmap/zouinkhim/dacapo_release/dacapo/dacapo/experiments/datasplits/simple_config.py", line 50, in get_paths
   raise Exception(f"No raw data found at {level_0} or {level_1} or {level_2}")
Exception: No raw data found at f{data_path}/test.zarr/raw or f{data_path}/test.zarr/test/raw or f{data_path}/test.zarr/test/**/raw
mprof: Sampling memory every 0.1s
running new process
```

**Comment by pattonw** [comment]
> Hi Will, you need to keep running the scripts of at least an hour. because generating the random crops takes ~2000 sec then i hit this error form your script : ![Screenshot 2024-12-03 at 10 14 16 AM](https://private-user-images.githubusercontent.com/5658590/392022945-13798a5b-ea3a-47ae-a1b7-ba519bc7f576.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzkzMDYsIm5iZiI6MTczMzIzOTAwNiwicGF0aCI6Ii81NjU4NTkwLzM5MjAyMjk0NS0xMzc5OGE1Yi1lYTNhLTQ3YWUtYTFiNy1iYTUxOWJjN2Y1NzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDNUMTUxNjQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWM1YWEzNzA4YjFmYmM2MzQ0OGEzYTliMjJmMDcwZDk3YTZiM2QzMzY2ZWZmNmRkZWZlNjAxNTM3NjZhOTg4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.R-bNnrufY0hf-Qcxsrn9rS_OYyiNnmczgzhQCsd28xQ)
> 
> ```
> Creating FileConfigStore:
> 	path: /groups/cellmap/cellmap/zouinkhim/base_model/dacapo_files/configs
> Training run test_run_will_3ddd
> Creating FileConfigStore:
> 	path: /groups/cellmap/cellmap/zouinkhim/base_model/dacapo_files/configs
> Starting/resuming training for run test_run_will_3ddd...
> Creating FileStatsStore:
> 	path    : /groups/cellmap/cellmap/zouinkhim/base_model/dacapo_files/stats
> Traceback (most recent call last):
>  File "/groups/cellmap/cellmap/zouinkhim/base_model/generate_run/profile_test_runs_3d_.py", line 128, in <module>
>    train(run_config.name)
>  File "/groups/cellmap/cellmap/zouinkhim/dacapo_release/dacapo/dacapo/train.py", line 47, in train
>    return train_run(run, do_validate)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/groups/cellmap/cellmap/zouinkhim/dacapo_release/dacapo/dacapo/train.py", line 66, in train_run
>    run.validation_scores.scores = stats_store.retrieve_validation_iteration_scores(
>    ^^^^^^^^^^^^^^^^^^^^^
>  File "/groups/cellmap/cellmap/zouinkhim/dacapo_release/dacapo/dacapo/experiments/run.py", line 160, in validation_scores
>    self.datasplit.validate,
>    ^^^^^^^^^^^^^^^^^^^^^^^
>  File "/groups/cellmap/cellmap/zouinkhim/dacapo_release/dacapo/dacapo/experiments/datasplits/simple_config.py", line 69, in validate
>    for x in self.get_paths(self.validate_group_name)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/groups/cellmap/cellmap/zouinkhim/dacapo_release/dacapo/dacapo/experiments/datasplits/simple_config.py", line 50, in get_paths
>    raise Exception(f"No raw data found at {level_0} or {level_1} or {level_2}")
> Exception: No raw data found at f{data_path}/test.zarr/raw or f{data_path}/test.zarr/test/raw or f{data_path}/test.zarr/test/**/raw
> mprof: Sampling memory every 0.1s
> running new process
> ```

Yeah I picked large roi's that took a few minutes to generate on my mac, depending on the computer generating those could take longer. Feel free to shrink them to something you can generate decently quickly.

I made a pull request with a small bugfix that should address the exception you got.

**Comment by pattonw** [comment]
> script: [here](https://gist.github.com/mzouink/962da76f2319249cc702866e3dbd38b5) when i use you script but with my data with 2d model it was ok: ![image](https://private-user-images.githubusercontent.com/5658590/392024281-5867668e-adf6-456f-a8a4-f08b64b1aee8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzk2NTIsIm5iZiI6MTczMzIzOTM1MiwicGF0aCI6Ii81NjU4NTkwLzM5MjAyNDI4MS01ODY3NjY4ZS1hZGY2LTQ1NmYtYThhNC1mMDhiNjRiMWFlZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDNUMTUyMjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2Q2Y2NmMWU5ZDdkMmVkYWQ5MzYzYjE1MjBjMTMyMWNlYzJlYTI1OGIyYzc0ZTdlM2FjYTUzOWFjZjEyYzE4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.pPCI_ZdPJVk9kqALigcAlTG8oE4IMCO6nzX2sr-aAL8)
> 
> but with 3d model the problem stated: ![image](https://private-user-images.githubusercontent.com/5658590/392024672-6e54af10-b13f-4dec-adc0-a6ceaeff6ebe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzk2NTIsIm5iZiI6MTczMzIzOTM1MiwicGF0aCI6Ii81NjU4NTkwLzM5MjAyNDY3Mi02ZTU0YWYxMC1iMTNmLTRkZWMtYWRjMC1hNmNlYWVmZjZlYmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDNUMTUyMjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGY4ZmI2NzBlNmI5M2U3MTcwYjg2M2Y4Y2YyOTgwNjJkM2IxNmYwYzUxNTIyYzg2OWRhN2IzNWQyZGZkMTBiZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ipEn-009v1poq5zxf7kzD6xWfvPr6pu0PP8034J8tpc) i am still doing more tests

Looks like the problem is present in both, but just on a smaller scale with the 2D model. Very strange that it is dependent on the model architecture

**Comment by pattonw** [comment]
Are these the 2 configs you are calling "2D" and "3D"?
```
# architecture_config = CNNectomeUNetConfig(
#     name="simple_unet_tt",
#     input_shape=(2, 64, 64),
#     eval_shape_increase=(8, 32, 32),
#     fmaps_in=1,
#     num_fmaps=8,
#     fmaps_out=8,
#     fmap_inc_factor=2,
#     downsample_factors=[(1, 2, 2), (1, 2, 2)],
#     kernel_size_down=[[(1, 3, 3)] * 2] * 3,
#     kernel_size_up=[[(1, 3, 3)] * 2] * 2,
#     constant_upsample=True,
#     padding="valid",
# )
# config_store.store_architecture_config(architecture_config)

architecture_config = CNNectomeUNetConfig(
    name="unet_tt",
    input_shape=(216, 216, 216),
    eval_shape_increase=(72, 72, 72),
    fmaps_in=1,
    num_fmaps=12,
    fmaps_out=72,
    fmap_inc_factor=6,
    downsample_factors=[(2, 2, 2), (3, 3, 3), (3, 3, 3)],
    constant_upsample=True,
    upsample_factors=[],
)
config_store.store_architecture_config(architecture_config)
```

One thing I notice is that the input shape is much higher for the 3D model than the 2D.
Just doing some quick math that looks like it would be using a lot of memory:
You have quite a lot of downsampling, I wouldn't be surprised if the context you need is around 84 voxels meaning your input data is potentially almost a 300 voxel cube. Assuming float 32, and an increase in volume size by a factor of about 3 for the rotation augmentation, thats almost `.3gb` for a single raw input.
Including all the other arrays (target, gt, mask, prediction, etc.) you could be getting up to about 1gb per batch. With 20 workers and a default cache size of 50, that means your pipeline could be using up to around 70gb just for holding data ready for training.
There's still something going wrong since thats still almost an order of magnitude off of the 500gb you see being occupied, but that just means its not surprising at all that the 2D model isn't running into the same memory problems

**Comment by mzouink** [comment]
yes that's what i mean by 2d / 3d

**Comment by mzouink** [comment]
update: 
your example: 
![image](https://github.com/user-attachments/assets/fe7cf603-8cd3-40c5-a834-92406fa93943)

Your example but with my datasplit:
![image](https://github.com/user-attachments/assets/2f14eb7d-5fa4-46d6-ba20-681fa1929256)

you example but with 3d model 
![image](https://github.com/user-attachments/assets/81c352a0-ed76-45ae-a539-567f4f5a5691)

with my data - 3d model: 
![image](https://github.com/user-attachments/assets/4767cd59-998f-4615-8c9b-ce71c9cd22f8)

I think the old datasplit have a leak somewhere.

**Comment by pattonw** [comment]
I narrowed down your data config to the BinarizeArrayConfig and ConcatArrayConfigs that seemed to be slow and memory expensive. I rewrote them to avoid using slicing to set data in a dask array and instead just use the `stack` method. That seems to resolve the issue on my small tests, do you want to test it on your large dataset?

**Comment by mzouink** [comment]
sure, thank you. i will test them

**Comment by pattonw** [comment]
I think this is fixed now
